SELECT TO_CHAR(SALES_DATE,'YYYY-MM-DD') AS SALES_DATE,PRODUCT_ID,USER_ID,SUM(SALES_AMOUNT) AS SALES_AMOUNT
FROM ONLINE_SALE
WHERE TO_CHAR(SALES_DATE,'YYYY-MM-DD')>='2022-03-01'
  AND TO_CHAR(SALES_DATE,'YYYY-MM-DD')<'2022-04-01'
GROUP BY SALES_DATE,PRODUCT_ID,USER_ID

UNION


SELECT TO_CHAR(SALES_DATE,'YYYY-MM-DD') AS SALES_DATE,PRODUCT_ID,NULL,SUM(SALES_AMOUNT)
FROM OFFLINE_SALE
WHERE TO_CHAR(SALES_DATE,'YYYY-MM-DD')>='2022-03-01'
  AND TO_CHAR(SALES_DATE,'YYYY-MM-DD')<'2022-04-01'
GROUP BY SALES_DATE, PRODUCT_ID
ORDER BY SALES_DATE,PRODUCT_ID;