-- 코드를 입력하세요
SELECT TO_CHAR(O.SALES_DATE,'YYYY') AS YEAR, TO_NUMBER(TO_CHAR(O.SALES_DATE,'MM')) AS MONTH, U.GENDER, count(distinct(U.USER_ID)) AS USERS
  FROM USER_INFO U, ONLINE_SALE O
 WHERE U.USER_ID = O.USER_ID
   AND U.USER_ID in
       (select U.USER_ID
        from USER_INFO U
        where U.GENDER IS NOT NULL)
 GROUP BY TO_CHAR(O.SALES_DATE,'YYYY'), TO_NUMBER(TO_CHAR(O.SALES_DATE,'MM')),U.GENDER
 ORDER BY YEAR, MONTH, U.GENDER;