-- 코드를 입력하세요
SELECT *
  FROM 
  (SELECT NAME, DATETIME
    FROM ANIMAL_INS
    WHERE ANIMAL_ID not IN
        (SELECT I.ANIMAL_ID
        FROM ANIMAL_INS I, ANIMAL_OUTS O
        WHERE I.ANIMAL_ID=O.ANIMAL_ID)
    ORDER BY DATETIME)
   where ROWNUM<=3;