-- 코드를 입력하세요
SELECT P.PRODUCT_ID, P.PRODUCT_NAME, SUM(O.AMOUNT)*P.PRICE AS TOTAL_SALES
  FROM FOOD_PRODUCT P, FOOD_ORDER O
 WHERE P.PRODUCT_ID=O.PRODUCT_ID
   AND TO_CHAR(O.PRODUCE_DATE,'YYYY-MM') = '2022-05'
   AND (P.PRODUCT_ID) IN
       (SELECT P.PRODUCT_ID
          FROM FOOD_PRODUCT P, FOOD_ORDER O
         WHERE P.PRODUCT_ID=O.PRODUCT_ID)
GROUP BY P.PRODUCT_ID,P.PRODUCT_NAME,P.PRICE
ORDER BY TOTAL_SALES DESC, P.PRODUCT_ID