-- 코드를 입력하세요
SELECT to_number(TO_CHAR(START_DATE,'MM')) AS MONTH, CAR_ID, COUNT(CAR_ID) AS RECORDS
  FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY 
  WHERE (CAR_ID IN
    (SELECT CAR_ID
    FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
    WHERE TO_CHAR(START_DATE,'YYYY-MM') BETWEEN '2022-08' AND '2022-10'
    GROUP BY CAR_ID
    HAVING COUNT(*)>=5))
 GROUP BY TO_NUMBER(TO_CHAR(START_DATE,'MM')), CAR_ID
 HAVING TO_NUMBER(TO_CHAR(START_DATE,'MM')) BETWEEN 8 AND 10
 ORDER BY MONTH, CAR_ID DESC;